### ISSUE TITLE
When saving, YAML fails to raise exception reading .kicad_pcb

### ISSUE THREAD

**Issue by sowbug** [xesscorp/kinjector#1]
* KinJector version: (Use `kinjector -V` to get this.)

kinjector 0.0.5

* KiCad version: (Use `Help => About KiCad => Copy Version Info` to get this.)

Version: 5.1.5-52549c5~84~ubuntu18.04.1, release build

* Python version: (Use `python -V` to get this.)

Python 3.6.9

* Operating System:

Ubuntu

### Description

I was trying to run the sample stuff at the top of https://xesscorp.github.io/kinjector/docs/_build/singlehtml/index.html.

### What I Did

```
kinjector --from my-first-keyboard.kicad_pcb --to my-first-keyboard-kinjector.json
```

... which worked, so I pared down the JSON and changed to the attached small file that only tried to move around the two resistors (incidentally, these started with the example in the neighbor project skidl's docs at https://xesscorp.github.io/skidl/docs/_site/)

Then I tried the other direction to write my changes to the PCB file:

```
kinjector -w --from my-first-keyboard-kinjector.json --to my-first-keyboard.kicad_pcb
```

At this point I tried to reopen the PCB file in KiCad and got a parsing error in the app, at which point I looked at the PCB file and found it had been overwritten with a copy of the JSON file, but reformatted in YAML. I did a little investigation and found that the YAML reader isn't raising an exception at https://github.com/xesscorp/kinjector/blob/master/kinjector/cli.py#L144 when it's trying to read in my .kicad_pcb file, so it just blasts out the tiny dictionary it had from reading the JSON into my soon-to-be-destroyed .kicad_pcb.

As an experiment, I replaced the YAML-replacing section with `raise Exception`, and it all worked as expected.

So the issue is YAML can't parse a .kicad_pcb, but it's not smart enough to know that it failed and that it should raise an exception.

By the way I had to run `cli.py` through the Python utility `2to3` because of a few print statements missing parens. No big deal.

Oh, rats, turns out I can't attach files not having specific extensions. I'll add the PCB file and then the JSON file as separate replies to this issue.

**Comment by sowbug** [comment]
Here's the PCB file:

```
(kicad_pcb (version 20171130) (host pcbnew 5.1.5-52549c5~84~ubuntu18.04.1)

  (general
    (thickness 1.6)
    (drawings 0)
    (tracks 0)
    (zones 0)
    (modules 2)
    (nets 4)
  )

  (page A4)
  (layers
    (0 F.Cu signal)
    (31 B.Cu signal)
    (32 B.Adhes user)
    (33 F.Adhes user)
    (34 B.Paste user)
    (35 F.Paste user)
    (36 B.SilkS user)
    (37 F.SilkS user)
    (38 B.Mask user)
    (39 F.Mask user)
    (40 Dwgs.User user)
    (41 Cmts.User user)
    (42 Eco1.User user)
    (43 Eco2.User user)
    (44 Edge.Cuts user)
    (45 Margin user)
    (46 B.CrtYd user)
    (47 F.CrtYd user)
    (48 B.Fab user)
    (49 F.Fab user)
  )

  (setup
    (last_trace_width 0.25)
    (trace_clearance 0.2)
    (zone_clearance 0.508)
    (zone_45_only no)
    (trace_min 0.2)
    (via_size 0.8)
    (via_drill 0.4)
    (via_min_size 0.4)
    (via_min_drill 0.3)
    (uvia_size 0.3)
    (uvia_drill 0.1)
    (uvias_allowed no)
    (uvia_min_size 0.2)
    (uvia_min_drill 0.1)
    (edge_width 0.05)
    (segment_width 0.2)
    (pcb_text_width 0.3)
    (pcb_text_size 1.5 1.5)
    (mod_edge_width 0.12)
    (mod_text_size 1 1)
    (mod_text_width 0.15)
    (pad_size 1.524 1.524)
    (pad_drill 0.762)
    (pad_to_mask_clearance 0.051)
    (solder_mask_min_width 0.25)
    (aux_axis_origin 0 0)
    (visible_elements FFFFFF7F)
    (pcbplotparams
      (layerselection 0x010fc_ffffffff)
      (usegerberextensions false)
      (usegerberattributes false)
      (usegerberadvancedattributes false)
      (creategerberjobfile false)
      (excludeedgelayer true)
      (linewidth 0.100000)
      (plotframeref false)
      (viasonmask false)
      (mode 1)
      (useauxorigin false)
      (hpglpennumber 1)
      (hpglpenspeed 20)
      (hpglpendiameter 15.000000)
      (psnegative false)
      (psa4output false)
      (plotreference true)
      (plotvalue true)
      (plotinvisibletext false)
      (padsonsilk false)
      (subtractmaskfromsilk false)
      (outputformat 1)
      (mirror false)
      (drillshape 1)
      (scaleselection 1)
      (outputdirectory ""))
  )

  (net 0 "")
  (net 1 VI)
  (net 2 VO)
  (net 3 GND)

  (net_class Default "This is the default net class."
    (clearance 0.2)
    (trace_width 0.25)
    (via_dia 0.8)
    (via_drill 0.4)
    (uvia_dia 0.3)
    (uvia_drill 0.1)
    (add_net GND)
    (add_net VI)
    (add_net VO)
  )

  (module Resistor_SMD:R_0805_2012Metric (layer F.Cu) (tedit 5B36C52B) (tstamp 5E3F9746)
    (at 147.755001 103.845001)
    (descr "Resistor SMD 0805 (2012 Metric), square (rectangular) end terminal, IPC_7351 nominal, (Body size source: https://docs.google.com/spreadsheets/d/1BsfQQcO9C6DZCsRaXUlFlo91Tg2WpOkGARC1WS5S8t0/edit?usp=sharing), generated with kicad-footprint-generator")
    (tags resistor)
    (path /top/18278248944485003214)
    (attr smd)
    (fp_text reference R1 (at 0 -1.65) (layer F.SilkS)
      (effects (font (size 1 1) (thickness 0.15)))
    )
    (fp_text value 1K (at 0 1.65) (layer F.Fab)
      (effects (font (size 1 1) (thickness 0.15)))
    )
    (fp_line (start -1 0.6) (end -1 -0.6) (layer F.Fab) (width 0.1))
    (fp_line (start -1 -0.6) (end 1 -0.6) (layer F.Fab) (width 0.1))
    (fp_line (start 1 -0.6) (end 1 0.6) (layer F.Fab) (width 0.1))
    (fp_line (start 1 0.6) (end -1 0.6) (layer F.Fab) (width 0.1))
    (fp_line (start -0.258578 -0.71) (end 0.258578 -0.71) (layer F.SilkS) (width 0.12))
    (fp_line (start -0.258578 0.71) (end 0.258578 0.71) (layer F.SilkS) (width 0.12))
    (fp_line (start -1.68 0.95) (end -1.68 -0.95) (layer F.CrtYd) (width 0.05))
    (fp_line (start -1.68 -0.95) (end 1.68 -0.95) (layer F.CrtYd) (width 0.05))
    (fp_line (start 1.68 -0.95) (end 1.68 0.95) (layer F.CrtYd) (width 0.05))
    (fp_line (start 1.68 0.95) (end -1.68 0.95) (layer F.CrtYd) (width 0.05))
    (fp_text user %R (at 0 0) (layer F.Fab)
      (effects (font (size 0.5 0.5) (thickness 0.08)))
    )
    (pad 1 smd roundrect (at -0.9375 0) (size 0.975 1.4) (layers F.Cu F.Paste F.Mask) (roundrect_rratio 0.25)
      (net 1 VI))
    (pad 2 smd roundrect (at 0.9375 0) (size 0.975 1.4) (layers F.Cu F.Paste F.Mask) (roundrect_rratio 0.25)
      (net 2 VO))
    (model ${KISYS3DMOD}/Resistor_SMD.3dshapes/R_0805_2012Metric.wrl
      (at (xyz 0 0 0))
      (scale (xyz 1 1 1))
      (rotate (xyz 0 0 0))
    )
  )

  (module Resistor_SMD:R_0805_2012Metric (layer F.Cu) (tedit 5B36C52B) (tstamp 5E3F9757)
    (at 152.165001 103.845001)
    (descr "Resistor SMD 0805 (2012 Metric), square (rectangular) end terminal, IPC_7351 nominal, (Body size source: https://docs.google.com/spreadsheets/d/1BsfQQcO9C6DZCsRaXUlFlo91Tg2WpOkGARC1WS5S8t0/edit?usp=sharing), generated with kicad-footprint-generator")
    (tags resistor)
    (path /top/13561241637457120831)
    (attr smd)
    (fp_text reference R2 (at 0 -1.65) (layer F.SilkS)
      (effects (font (size 1 1) (thickness 0.15)))
    )
    (fp_text value 500 (at 0 1.65) (layer F.Fab)
      (effects (font (size 1 1) (thickness 0.15)))
    )
    (fp_text user %R (at 0 0) (layer F.Fab)
      (effects (font (size 0.5 0.5) (thickness 0.08)))
    )
    (fp_line (start 1.68 0.95) (end -1.68 0.95) (layer F.CrtYd) (width 0.05))
    (fp_line (start 1.68 -0.95) (end 1.68 0.95) (layer F.CrtYd) (width 0.05))
    (fp_line (start -1.68 -0.95) (end 1.68 -0.95) (layer F.CrtYd) (width 0.05))
    (fp_line (start -1.68 0.95) (end -1.68 -0.95) (layer F.CrtYd) (width 0.05))
    (fp_line (start -0.258578 0.71) (end 0.258578 0.71) (layer F.SilkS) (width 0.12))
    (fp_line (start -0.258578 -0.71) (end 0.258578 -0.71) (layer F.SilkS) (width 0.12))
    (fp_line (start 1 0.6) (end -1 0.6) (layer F.Fab) (width 0.1))
    (fp_line (start 1 -0.6) (end 1 0.6) (layer F.Fab) (width 0.1))
    (fp_line (start -1 -0.6) (end 1 -0.6) (layer F.Fab) (width 0.1))
    (fp_line (start -1 0.6) (end -1 -0.6) (layer F.Fab) (width 0.1))
    (pad 2 smd roundrect (at 0.9375 0) (size 0.975 1.4) (layers F.Cu F.Paste F.Mask) (roundrect_rratio 0.25)
      (net 3 GND))
    (pad 1 smd roundrect (at -0.9375 0) (size 0.975 1.4) (layers F.Cu F.Paste F.Mask) (roundrect_rratio 0.25)
      (net 2 VO))
    (model ${KISYS3DMOD}/Resistor_SMD.3dshapes/R_0805_2012Metric.wrl
      (at (xyz 0 0 0))
      (scale (xyz 1 1 1))
      (rotate (xyz 0 0 0))
    )
  )

)
```

**Comment by sowbug** [comment]
And here's my JSON file:

```
{
    "board": {
        "modules": {
            "R1": {
                "position": {
                    "x": 147755001,
                    "y": 113845001,
                    "angle": 0.0,
                    "side": "top"
                }
            },
            "R2": { 
                "position": {
                    "x": 152165001,
                    "y": 73845001,
                    "angle": 0.0,
                    "side": "top"
                }
            }
        }
    }
}
```

**Comment by sowbug** [comment]
OK, I think I know what's going on here. The first failed read by `json.load` probably changes the file pointer `fp`, so that when it gets to the YAML section, it reads the end of the file, which the YAML parser might consider a valid (if empty) file:

```
$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json, yaml
>>> f = open("my-first-keyboard.kicad_pcb", "r")
>>> fd = yaml.load(f, Loader=yaml.Loader)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miket/.local/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/miket/.local/lib/python3.6/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/home/miket/.local/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/miket/.local/lib/python3.6/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/home/miket/.local/lib/python3.6/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/home/miket/.local/lib/python3.6/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/home/miket/.local/lib/python3.6/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/home/miket/.local/lib/python3.6/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/home/miket/.local/lib/python3.6/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/home/miket/src/my-first-keyboard/my-first-keyboard.kicad_pcb", line 112, column 116
>>> f = open("my-first-keyboard.kicad_pcb", "r")
>>> fd = json.load(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> fd = yaml.load(f, Loader=yaml.Loader)
>>>
```

See: if you yaml.load() on the freshly-opened file pointer, it correctly raises. But if you do it on the same file pointer that json.load() just exploded with, then yaml.load() doesn't complain.

I suppose the cleanest fix would be to re-open the file for each load attempt, rather than assuming we can keep hammering the first file pointer again and again. Maybe this changed with Python 3.

**Comment by sowbug** [comment]
... or perhaps add the `fp.seek(0)` that you already have in an earlier block of code, for example at https://github.com/xesscorp/kinjector/blob/master/kinjector/cli.py#L112. I would try this myself, but I need to go to bed.

**Comment by sowbug** [comment]
I thought I'd fixed this, but neither the `fp.seek(0)` nor a close/open changes the behavior. I'm confused why I get a YAML parser exception in the REPL, but not in the code. So my PR is wrong. I'll continue to investigate.
